In [ ]:
# 1D array Print

In [9]:

import numpy as np
arr_1D = np.array([3,4,5,6])
print(arr_1D)

[3 4 5 6]


# Find array type

In [10]:
type(arr_1D)

numpy.ndarray

# Find dimension

In [11]:
arr_1D.ndim

1

# Create 2D array and find Data type, array size, array shape

In [13]:
arr_2d = np.array(([2,3,4],[5,6,7]))
print(arr_2d)

[[2 3 4]
 [5 6 7]]


In [15]:
arr_2d.dtype

dtype('int64')

In [16]:
arr_2d.size


6

In [17]:
arr_2d.shape


(2, 3)

# Create an 3D array

In [43]:
mx_2s = np.array(([1,1,1],[1,1,1],[1,1,1]))
print(mx_2s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Ones function use only for '1' elements print

In [44]:
mx_2s=np.ones((4))
print(mx_2s)

[1. 1. 1. 1.]


In [45]:
mx_2s.dtype #Data type function use

dtype('float64')

In [46]:
mx_2s = np.ones((3,4)) # ( 3 Row and 4 Col)
print(mx_2s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
mx_2s = np.ones ((3,4), dtype = int) # convert float to int data
print(mx_2s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [51]:
mx_0s = np.zeros((3,6))   # zeros function use only for '0' elements print
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [55]:
mx_0s = np.zeros((3,6),dtype=bool) # Boolean conversion 
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [56]:
mx_0s = np.zeros((3,6),dtype=str)  # String conversion
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [61]:
em_str = ''     # Empty string return to boolean 
print(bool(em_str))

False


In [60]:
em_mx = np.empty((3,3))
print(em_mx)

[[1.e-323 1.e-323 1.e-323]
 [2.e-323 2.e-323 2.e-323]
 [3.e-323 3.e-323 3.e-323]]


In [5]:
import numpy as np

In [35]:
ar_1a = np.arange(1,17)
print(ar_1a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [36]:
arr = np.arange(1,11,3) # Arange function Use
print(ar_1d)

[1.         2.33333333 3.66666667 5.        ]


In [37]:
ar1d = np.linspace(1,5,4) #Linespace Function use spaces generated
print(ar_1d)

[1.         2.33333333 3.66666667 5.        ]


In [32]:
ar_2a = ar_1a.reshape(2,8) # Reshape 1D array to 2D array
print(ar_2a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [47]:
ar_3d = ar_1a.reshape(4,1,4) #1D to 3D matrix conversion
print(ar_3d)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]

 [[13 14 15 16]]]


In [50]:
ar=np.arange(1,17).reshape(4,4) # Arange & reshape function use together
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [52]:
ar.ravel() # multidimension function convert into 1D array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [55]:
ar.flatten() # same work as ravel 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [58]:
ar.transpose() # Row convert into col (always transpose as same as T denoted [ar.T])

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])